name: ParallelCluster Cookbook CI

on: [push, pull_request]

jobs:
  depcheck:
    runs-on: ubuntu-latest
    name: DepCheck
    steps:
      - uses: actions/checkout@v2
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          path: '.'
          format: 'HTML'
          project: 'aws-parallelcluster-cookbook'
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
  ruby:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        name:
          - Setup Ruby
        include:
          - name: Setup Ruby

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install --with style
      - name: Run Rubocop
        run: rubocop
      - name: Run Foodcritic
        # FC071 is a check for a LICENSE file.
        # It doesn't like that ours is named LICENSE.txt.
        run: foodcritic -t '~FC071' .
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        name:
          - Python 3.7 Tests
          - Python 3.8 Tests
          - Python 3.9 Tests
          - Code Checks
        include:
          - name: Python 3.7 Tests
            python: 3.7
            toxenv: py37
          - name: Python 3.8 Tests
            python: 3.8
            toxenv: py38
          - name: Python 3.9 Tests
            python: 3.9
            toxenv: py39
          - name: Code Checks
            python: 3.9
            toxenv: code-linters

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e ${{ matrix.toxenv }}
