name: ParallelCluster Cookbook System Test Ubuntu

on:
  push:
    branches:
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  systemtest-build:
    runs-on: ubuntu-latest
    name: SystemTestUbuntu
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Install
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./system_tests/Dockerfile.ubuntu
          push: true
          tags: localhost:5000/pcluster/chef-base:ubuntu
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Configure
        run: docker run -i -v ${{ github.workspace }}:/build -v ${{ github.workspace }}/system_tests/dna.json:/etc/chef/dna.json localhost:5000/pcluster/chef-base:ubuntu /build/system_tests/systemd; echo $?
